# Generated by Django 5.0.2 on 2024-02-20 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=200)),
                ('service_image', models.FileField(blank=True, default='', upload_to='media/uploads')),
                ('service_discription', models.CharField(blank=True, max_length=500)),
                ('content', models.CharField(blank=True, max_length=2000)),
                ('cover_image', models.FileField(blank=True, default='', upload_to='media/uploads')),
                ('url', models.CharField(blank=True, max_length=100)),
                ('content2', models.CharField(blank=True, max_length=2000)),
            ],
        ),
    ]
