# Generated by Django 5.0.2 on 2024-03-02 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='content2',
        ),
        migrations.RemoveField(
            model_name='service',
            name='url',
        ),
    ]
