# Generated by Django 5.0.2 on 2024-03-24 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_remove_service_cover_image_service_benefit_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='section2_content',
            new_name='section_3_content',
        ),
    ]
