# Generated by Django 5.0.2 on 2024-02-17 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technology_name', models.CharField(max_length=200)),
                ('technology_discription', models.CharField(max_length=500, null=True)),
                ('content', models.CharField(max_length=1000)),
                ('technology_image', models.FileField(blank=True, default='', upload_to='media/uploads')),
            ],
        ),
    ]
