# Generated by Django 5.0.2 on 2024-03-03 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technologies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='url',
            field=models.SlugField(default='', max_length=200),
        ),
    ]
