# Generated by Django 5.0.2 on 2024-03-24 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technologies', '0002_technology_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='benefit_1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='technology',
            name='benefit_1_disc',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='technology',
            name='benefit_2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='technology',
            name='benefit_2_disc',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='technology',
            name='benefit_3',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='technology',
            name='benefit_3_disc',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='technology',
            name='benefit_4',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='technology',
            name='benefit_4_disc',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='technology',
            name='h1',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='technology',
            name='h2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='technology',
            name='usage_1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='technology',
            name='usage_1_disc',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='technology',
            name='usage_2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='technology',
            name='usage_2_disc',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='technology',
            name='usage_3',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='technology',
            name='usage_3_disc',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='technology',
            name='usage_4',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='technology',
            name='usage_4_disc',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='technology',
            name='content',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='technology',
            name='url',
            field=models.SlugField(max_length=200),
        ),
    ]
