# Generated by Django 5.0.2 on 2024-03-05 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('url', models.SlugField(max_length=200)),
                ('product_image', models.FileField(blank=True, default='', upload_to='media/uploads')),
                ('h1', models.CharField(max_length=200)),
                ('product_discription', models.CharField(max_length=500, null=True)),
                ('h2', models.CharField(max_length=200, null=True)),
                ('content', models.CharField(max_length=500, null=True)),
                ('process_1', models.CharField(max_length=200, null=True)),
                ('process_1_disc', models.CharField(max_length=500, null=True)),
                ('process_2', models.CharField(max_length=200, null=True)),
                ('process_2_disc', models.CharField(max_length=500, null=True)),
                ('process_3', models.CharField(max_length=200, null=True)),
                ('process_3_disc', models.CharField(max_length=500, null=True)),
                ('process_4', models.CharField(max_length=200, null=True)),
                ('process_4_disc', models.CharField(max_length=500, null=True)),
                ('usage_1', models.CharField(max_length=200, null=True)),
                ('usage_1_disc', models.CharField(max_length=500, null=True)),
                ('usage_2', models.CharField(max_length=200, null=True)),
                ('usage_2_disc', models.CharField(max_length=500, null=True)),
                ('usage_3', models.CharField(max_length=200, null=True)),
                ('usage_3_disc', models.CharField(max_length=500, null=True)),
                ('usage_4', models.CharField(max_length=200, null=True)),
                ('usage_4_disc', models.CharField(max_length=500, null=True)),
                ('dotnet', models.BooleanField()),
                ('java', models.BooleanField()),
                ('python', models.BooleanField()),
                ('php', models.BooleanField()),
                ('nodejs', models.BooleanField()),
                ('html', models.BooleanField()),
                ('css', models.BooleanField()),
                ('javascript', models.BooleanField()),
                ('react', models.BooleanField()),
                ('vue', models.BooleanField()),
                ('angular', models.BooleanField()),
                ('aws', models.BooleanField()),
                ('azure', models.BooleanField()),
                ('googlecloud', models.BooleanField()),
                ('ios', models.BooleanField()),
                ('android', models.BooleanField()),
                ('reactnative', models.BooleanField()),
                ('flutter', models.BooleanField()),
                ('kotlin', models.BooleanField()),
                ('sqlserver', models.BooleanField()),
                ('mysql', models.BooleanField()),
                ('postgres', models.BooleanField()),
                ('mongodb', models.BooleanField()),
                ('paypal', models.BooleanField()),
                ('stripe', models.BooleanField()),
                ('visa', models.BooleanField()),
                ('gpay', models.BooleanField()),
                ('cover_image', models.FileField(blank=True, default='', upload_to='media/uploads')),
            ],
        ),
    ]
