# Generated by Django 5.0 on 2024-02-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_image', models.FileField(null=True, upload_to='media/uploads')),
                ('product_discription', models.CharField(max_length=500, null=True)),
                ('content', models.CharField(max_length=1000)),
                ('cover_image', models.FileField(null=True, upload_to='media/uploads')),
            ],
        ),
    ]
