# Generated by Django 5.0 on 2024-02-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cover_image',
            field=models.FileField(blank=True, default='', upload_to='media/uploads'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.FileField(blank=True, default='', upload_to='media/uploads'),
        ),
    ]
