# Generated by Django 5.0.2 on 2024-03-05 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='h1',
            field=models.CharField(default='', max_length=200),
        ),
    ]
