# Generated by Django 5.0.2 on 2024-03-03 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_cover_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='url',
            field=models.SlugField(blank=True, max_length=10),
        ),
    ]
