# Generated by Django 5.0.2 on 2024-03-02 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='url',
            field=models.SlugField(default=models.CharField(max_length=100), max_length=200),
        ),
    ]
