# Generated by Django 5.0.2 on 2024-03-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company_disc',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='job',
            name='company_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='job',
            name='job_qualifications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='job',
            name='job_requirement',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='job',
            name='job_skills',
            field=models.TextField(blank=True),
        ),
    ]
