# Generated by Django 5.0.2 on 2024-03-02 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_job_company_disc_job_company_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='url',
        ),
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.CharField(choices=[('Per Month', 'P/ Month'), ('Per Hour', 'P/ Hour'), ('Per Year', 'P/ Year')], default='', max_length=20),
        ),
    ]
