# Generated by Django 5.0.2 on 2024-03-02 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_remove_job_url_job_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='salary_type',
            field=models.CharField(choices=[('Per Month', 'P/ Month'), ('Per Hour', 'P/ Hour'), ('Per Year', 'P/ Year')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.CharField(default='', max_length=10),
        ),
    ]
