from django import forms


SERVICES_FORM_WIDGET = {
    'service_name': forms.TextInput(attrs={'class': 'form-control'}),
    'url': forms.TextInput(attrs={'class': 'form-control'}),
    'h1': forms.TextInput(attrs={'class': 'form-control'}),
    'service_discription': forms.TextInput(attrs={'class': 'form-control'}),
    'h2': forms.TextInput(attrs={'class': 'form-control'}),
    'content': forms.TextInput(attrs={'class': 'form-control'}),
    'benefit_1': forms.TextInput(attrs={'class': 'form-control'}),
    'benefit_1_disc': forms.TextInput(attrs={'class': 'form-control'}),
    'benefit_2': forms.TextInput(attrs={'class': 'form-control'}),
    'benefit_2_disc': forms.TextInput(attrs={'class': 'form-control'}),
    'benefit_3': forms.TextInput(attrs={'class': 'form-control'}),
    'benefit_3_disc': forms.TextInput(attrs={'class': 'form-control'}),
    'benefit_4': forms.TextInput(attrs={'class': 'form-control'}),
    'benefit_4_disc': forms.TextInput(attrs={'class': 'form-control'}),   
    'section_2_h2': forms.TextInput(attrs={'class': 'form-control'}),   
    'service_1': forms.TextInput(attrs={'class': 'form-control'}),   
    'service_1_disc': forms.TextInput(attrs={'class': 'form-control'}),     
    'service_2': forms.TextInput(attrs={'class': 'form-control'}),   
    'service_2_disc': forms.TextInput(attrs={'class': 'form-control'}),     
    'service_3': forms.TextInput(attrs={'class': 'form-control'}),   
    'service_3_disc': forms.TextInput(attrs={'class': 'form-control'}),     
    'service_4': forms.TextInput(attrs={'class': 'form-control'}),   
    'service_4_disc': forms.TextInput(attrs={'class': 'form-control'}),     
    'service_5': forms.TextInput(attrs={'class': 'form-control'}),   
    'service_5_disc': forms.TextInput(attrs={'class': 'form-control'}),     
    'service_6': forms.TextInput(attrs={'class': 'form-control'}),   
    'service_6_disc': forms.TextInput(attrs={'class': 'form-control'}),   
    'section_3_h2': forms.TextInput(attrs={'class': 'form-control'}),   
    'section_3_content': forms.TextInput(attrs={'class': 'form-control'}),   

    }