# Generated by Django 4.2.9 on 2024-01-30 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_rename_clientqueries_clientquery'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientquery',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
